### ISSUE TITLE
Issues with input_number

### ISSUE THREAD

**Issue by VirtualL** [custom-cards/vertical-stack-in-card#18]
Hi, I getting this Warning : 
```https://MYSERVER.COM/frontend_latest/eb618cf11a4eca6918ea.chunk.js:266:14994 TypeError: null is not an object (evaluating 'this.shadowRoot.querySelector("paper-slider").offsetWidth')```

The config:
```
      - type: custom:vertical-stack-in-card
        cards:   
          - type: markdown
            content: >
              ### Alarm Clock

          - type: entities
            entities:
              - input_boolean.alarm_clock_status
              - entity: sensor.alarm_clock_time
                name: Selcted Time
              - input_number.alarm_clock_minute
              - input_number.alarm_clock_hour
```

If I will remove the input_number entities , the warning will disappear 

Thanks again!

**Comment by VirtualL** [comment]
Hi , I just checked again and the issue happens **only in Safari Browser**  and when I use this card , in the built-in vertical-stack its not make this warning.

Please make this issue open again.
basic config to get this warning:
```
      - type: custom:vertical-stack-in-card
        cards:   
          - type: entities
            entities:
              - input_number.alarm_clock_hour
              - input_number.alarm_clock_minute
```
