### ISSUE TITLE
2 kinds of warnings when using "vertical-stack" card

### ISSUE THREAD

**Issue by VirtualL** [custom-cards/vertical-stack-in-card#19]
Hi, I getting  2 warnings , 
**In Safari (Latest Version 11.1.1 (13605.2.8) ) only  :** 
`https://MYSERVER.COM/local/custom_components/vertical-stack-in-card.js?v=0.0.6:61:74 TypeError: null is not an object (evaluating 'searchEles[i].shadowRoot.querySelector('ha-card').style')`
**In Gogle Chrome (Latest Version 67.0.3396.99) only :**
`https://MYSERVER.COM/local/custom_components/vertical-stack-in-card.js?v=0.0.6:61:74 Uncaught TypeError: Cannot read property 'style' of null`

The config:
```
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            entities:
              - light.living_room_color_bulb
          - type: vertical-stack
            cards:
              - type: horizontal-stack
                cards:
                  - type: picture-glance
                    image: /local/MyEntities/livingroom.jpeg
                    entities:
                      - light.white_bulb
                      - light.living_room_color_bulb
                  - type: picture-glance
                    image: /local/MyEntities/kitchen.jpeg
                    entities:
                      - light.sonoff_light
                      - light.philips_bulb
                ######      
              - type: horizontal-stack
                cards:
                  - type: picture-glance
                    image: /local/MyEntities/hallway.jpeg
                    entities:
                      - light.sonoff_hallway_light
                      - light.gateway_light_34ce0088d2f7
                  - type: picture-glance
                    image: /local/MyEntities/bedroom.jpeg
                    entities:
                      - light.desk_lamp
                      - switch.bedroom_fan_light
```
i want do it this way because like this its look:
<img width="473" alt="screen shot 2018-08-07 at 10 10 17" src="https://user-images.githubusercontent.com/10164935/43760785-cda28726-9a2b-11e8-8484-43863b040b2c.png">

but if its will be without the "vertical-stack cards" its will be look like this: (no borders)
<img width="470" alt="screen shot 2018-08-07 at 10 25 35" src="https://user-images.githubusercontent.com/10164935/43760960-4760c000-9a2c-11e8-9533-05866be1e4aa.png">

Thanks again!

**Comment by ofekashery** [comment]
Try this:
```
      - type: custom:vertical-stack-in-card
        cards:
          - type: entities
            entities:
              - light.living_room_color_bulb
          - type: horizontal-stack
            cards:
              - type: picture-glance
                image: /local/MyEntities/livingroom.jpeg
                entities:
                  - light.white_bulb
                  - light.living_room_color_bulb
              - type: picture-glance
                image: /local/MyEntities/kitchen.jpeg
                entities:
                  - light.sonoff_light
                  - light.philips_bulb
            ######      
          - type: horizontal-stack
            cards:
              - type: picture-glance
                image: /local/MyEntities/hallway.jpeg
                entities:
                  - light.sonoff_hallway_light
                  - light.gateway_light_34ce0088d2f7
              - type: picture-glance
                image: /local/MyEntities/bedroom.jpeg
                entities:
                  - light.desk_lamp
                  - switch.bedroom_fan_light
```

Anyway, I'll fix it soon
