### ISSUE TITLE
"element.setConfig is not a function" in Android Chrome browser

### ISSUE THREAD

**Issue by thegame3202** [custom-cards/vertical-stack-in-card#22]
LOVE the look of this card, and it works great on desktop browsers, but Chrome Canary, regular Chrome, and the Samsung Internet browser give me the above error.

I DO have javascript_version: latest in my config as well.

Any ideas how to fix?  Thank you!

**Comment by ofekashery** [comment]
Hey, what is your Home Assistant version?

**Comment by Mikei386** [comment]
Hi there,

I have exactly the same problem.
I was able to narrow it down to a combination of the custom button-card and the vertical-stack-in-card.

It appears that the button-card is “loading” for quite a while until it shows up.
Combining it with a vertical-stack-in-card  results in showing an error for the complete card, until the button is loaded.

> element.setConfig is not a function. (In element.setConfig(item), element.setConfig is undefined) 

Separateing the cards with the “normal” vertical stack card works and shows how the button card shows up a few seconds later, after it’s loaded.

Also, all of that happens only when loading the site the first time. Refreshing it a few times after another doesn’t show the error anymore.

Maybe this helps someone

**Comment by damusmf** [comment]
HA 0.85.1

same issue with this card and button card.  used to work after a few reloads but now it is constant on v.0.1.0 of vertical stack in card

**Comment by Dielee** [comment]
Same here... my config: 

```
      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:simple-thermostat
            entity: climate.oeq1684915
            sensors:
              - entity: sensor.wohnzimmer_feuchtig
              - entity: sensor.wohnzimmer_tmp_template
              - entity: sensor.wohnzimmer_tmp
              - entity: binary_sensor.oeq1375758_state
                name: Fenster
            hide:
              mode: true
              temperature: true
          - type: custom:simple-thermostat
            entity: climate.oeq1685747
            sensors:
              - entity: sensor.kueche_tmp
              - entity: binary_sensor.oeq1027067_state
                name: Fenster
            hide:
               mode: true
               temperature: true
          - type: custom:simple-thermostat
            entity: climate.oeq1686946
            sensors:
              - entity: sensor.badezimmer_tmp
              - entity: binary_sensor.oeq1376840_state
                name: Fenster
            hide:
              mode: true
              temperature: true
          - type: entities
            entities:
             - entity: input_boolean.heizung
             - entity: input_boolean.urlaub
```
