### ISSUE TITLE
Error log filling

### ISSUE THREAD

**Issue by INTELBB** [custom-cards/vertical-stack-in-card#24]
I'm using latest 0.0.6 version
My error log keeps filing every time I open tab with this component in it.

`https://secert.url.org/local/components/vertical-stack-in-card.js?v=0.0.6:1:1 Uncaught SyntaxError: Identifier 'VerticalStackInCard' has already been declared`
`https://secret.url.org/local/components/vertical-stack-in-card.js?v=0.0.6:61:74 Uncaught TypeError: Cannot read property 'style' of null`
Here is my Lovelace config:

```
          - type: custom:vertical-stack-in-card
            cards: 
              - type: horizontal-stack
                cards:
                  - type: "custom:button-card"
                    entity: group.svjetla
                    icon: mdi:lightbulb-outline
                    color: auto
                    action: more_info
                    default_color: rgb(255, 233, 155)
                    color_type: icon
                    name: Rasvjeta
                  - type: "custom:button-card"
                    entity: light.rgb_traka
                    icon: mdi:palette
                    color: auto
                    color_type: icon
                    name: RGB
                    default_color: rgb(255, 233, 155)
                  - type: "custom:button-card"
                    entity: light.luster
                    icon: mdi:ceiling-light
                    name: Luster
                    color: auto
                    default_color: rgb(255, 233, 155)
                    color_type: icon
                  - type: "custom:button-card"
                    entity: light.led_traka
                    icon: mdi:hotel
                    name: Krevet
                    color: auto
                    default_color: rgb(255, 233, 155)
                    color_type: icon
    
```

And resources:

```
  - url: /local/components/vertical-stack-in-card.js?v=0.0.6
    type: js
```
