### ISSUE TITLE
Errors in log with virtual-stack-in-card and swipe-card

### ISSUE THREAD

**Issue by bieniu** [custom-cards/vertical-stack-in-card#25]
I have a lot of errors in log with vertical-stack-in-card after us it with [swipe-card](https://github.com/bramkragten/custom-ui/tree/master/swipe-card).
```
https://_redacted_/local/lovelace/vertical-stack-in-card.js?v=0.0.6:58:45 Uncaught TypeError: Cannot read property 'childNodes' of null
```
My config:
```
         - type: custom:vertical-stack-in-card
            title: 'Salon'
            cards:
              - type: custom:swipe-card
                cards:
                  - type: sensor
                    entity: sensor.temperature_salon
                  - type: sensor
                    entity: sensor.humidity_salon
                  - type: sensor
                    entity: sensor.co2_salon
                  - type: sensor
                    entity: sensor.illumination_salon
              - type: entities
                show_header_toggle: false
                entities:
                  - entity: binary_sensor.motion_salon
                    secondary_info: last-changed
                  - climate.thermostat_salon
                  - switch.light_bulbs_salon
                  - switch.light_leds_salon
                  - light.lamp_salon
                  - input_select.light_scenes_salon
                  - input_select.salon_harmony
```
