### ISSUE TITLE
gauge card not showing up

### ISSUE THREAD

**Issue by Ernst79** [custom-cards/vertical-stack-in-card#33]
I'm having problems with showing gauges in the vertical-stack-in-card. They are not showing up anymore, while they did in the past. If I show the gauge card normally (not in the vertical-stack-in-card), it works fine. I don't remember when this changed. 

My code is as follows. 

    - icon: mdi:access-point-network
      id: netwerk
      cards: 
        - type: custom:vertical-stack-in-card
          title: internet
          cards:
          - type: gauge
            title: download
            entity: sensor.speedtest_download
          - type: gauge
            title: upload
            entity: sensor.speedtest_upload
          - type: gauge
            title: ping
            entity: sensor.speedtest_ping

Any idea what is going wrong?

**Comment by bieniu** [comment]
I have the same issue. Gauge card doesn't show and no errors in log.
```
- type: custom:vertical-stack-in-card
   title: 'UPS'
   cards:
     - type: entities
       show_header_toggle: false
       entities:
         - sensor.ups_status
         - sensor.ups_battery_charge
       - type: gauge
         title: 'Obciążenie'
         entity: sensor.ups_load
         severity:
           green: 0
           yellow: 40
           red: 70
```
