### ISSUE TITLE
Padding missing

### ISSUE THREAD

**Issue by hulkhaugen** [custom-cards/vertical-stack-in-card#34]
I'm trying to put two cards inside this card, but the padding is gone for the fold-entity-row. Could also be others, hard to say due to their layout. Please see photo, one standalone fold-entity-row with correct padding, and one inside a vertical-stack-in-card w/o padding.

EDIT: I'm using HA v0.81.6

![lovelace](https://user-images.githubusercontent.com/1409758/49698816-476b1b00-fbc9-11e8-91c0-8a3741b9a11b.PNG)

```
  - title: Avansert
    id: avansert
    icon: mdi:settings
    cards:
      - type: entities
        title: Økonomi
        entities:
        - type: custom:fold-entity-row
          head: sensor.dnb_ask_beholding
          items:
            - sensor.dnb_health_care_1_dag
            - sensor.dnb_health_care_kurs
            - sensor.dnb_teknologi_1_dag
            - sensor.dnb_teknologi_kurs

      - type: custom:vertical-stack-in-card
        cards:
          - type: custom:weather-card
            title: Været
            entity_weather: weather.metno
            entity_sun: sun.sun
            entity_wind: sensor.vindstyrke_tekst
          - type: glance
            entities:
             - sun.sun
             - sensor.current_uv_level
             - sensor.current_uv_index
             - sensor.max_uv_index

      - type: custom:vertical-stack-in-card
        title: Strømforbruk
        cards:
          - type: gauge
            entity: sensor.electricity_price
            title: 'Strømpris'
            unit_of_measurement: 'kr'
            min: 0
            max: 1.8
            severity:
              green: 0
              yellow: 0.6
              red: 1.2
          - type: custom:fold-entity-row
            head: sensor.electricity_price
            items:
              - sensor.qubino_zmnhdd1_flush_dimmer_power
              - sensor.fibaro_system_fgd212_dimmer_2_power
              - sensor.fibaro_system_fgd212_dimmer_2_power_3
              - sensor.fibaro_system_fgd212_dimmer_2_power_5
              - sensor.fibaro_system_fgd212_dimmer_2_power_7
              - sensor.fibaro_system_fgd212_dimmer_2_power_10
              - sensor.fibaro_system_fgd212_dimmer_2_power_12
              - sensor.fibaro_system_fgwpef_wall_plug_gen5_power
```
