### ISSUE TITLE
please allow entity: divider - feature request

### ISSUE THREAD

**Issue by Mariusthvdb** [custom-cards/vertical-stack-in-card#36]
HI,
as per title, it would be very nice if we could use the type: divider in the vertical stack.

not sure if Im doing it wrong, but

```
  - type: custom:vertical-stack-in-card
    title: Raspberry Pi3
    cards:
      - type: entities
        show_header_toggle: false
        entities:
          - sensor.rpi_last_boot_macro
          - sensor.last_boot
          - device_tracker.hassio
          - binary_sensor.hassio
      - type: divider
      - type: glance
        entities:
        - sensor.disk_free_home
        - entity: sensor.disk_use_home
          name: Disk use
        - entity: sensor.disk_use_percent_home
          name: Disk %
        - entity: sensor.memory_use
          name: Mem Use
        - entity: sensor.memory_use_percent
          name: Mem %
      - type: entities
        show_header_toggle: false
        entities:
        - sensor.ipv4_address_eth0
        - sensor.external_ip
```

results in:

![schermafbeelding 2018-12-17 om 23 44 49](https://user-images.githubusercontent.com/33354141/50120418-c4476600-0255-11e9-8b39-81529afcf367.jpg)

thanks for considering
