### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by scstraus** [custom-cards/vertical-stack-in-card#44]
Hi,

This card is exactly what I've been needing! Unfortunately when I try to use it on 0.84.6 I get the following error in the log:

https://MYHOST:8123/local/vertical-stack-in-card.js?v=0.0.9:7:1 Uncaught SyntaxError: Unexpected token <

In the lovelace UI it says the card doesn't exist. Here is my resources (as you can see I have a lot of custom cards, they all work well- your .js is sitting with all the other ones in my www folder with same permissions and everything).

```
title: Home

# Include external resources

resources:

  - url: /local/vertical-stack-in-card.js?v=0.0.9
    type: js
  - url: /local/mini-media-player-bundle.js?v=0.9.2
    type: module
  - url: https://unpkg.com/moment@2.22.2/moment.js
    type: js
  - url: /local/custom_ui/calendar-card/calendar-card.js?v=1.0.1
    type: module  
  - url: /local/button-card.js
    type: module
  - url: /local/air-visual-card.js 
    type: js
  - url: /local/custom-weather-card-chart.js
    type: module
  - url: /local/simple-thermostat/simple-thermostat.js?v=1
    type: module
```

Here is the stack I tried to make, was a straight replacement for a vertical stack that was working fine:

```
    - type: custom:vertical-stack-in-card
      title: Entrance
      cards:
    
      - type: history-graph
        title: 'Entrance'
        entities:
        - climate.entrance


      - type: entities
        entities:
        - climate.entrance
```
