### ISSUE TITLE
Padding and boxshadow isn't removed

### ISSUE THREAD

**Issue by thrawnarn** [custom-cards/vertical-stack-in-card#5]
When placed inside a vertical-stack the padding and boxshadow isn't removed immediately. Sometimes it disappears after a second, sometimes after 5 or so. It has to set the hass object (line 46) a second time for the boxShadow and padding to disappear. I'm running the latest version.
I would debug it more myself, but I ain't got time right now. If no one has solved it next weekend I may have a second look at it.

Screenshot (I've marked the problems in a red box): 
![screenshot_4](https://user-images.githubusercontent.com/5276026/43633469-a0dba1f2-9709-11e8-9a57-4511f6403769.png)

Configuration:
```
views:
  - icon: mdi:home
    title: Start
    cards:
      - type: vertical-stack
        cards:
          - type: custom:vertical-stack-in-card
            title: 'Vardagsrummet'
            cards:
              - type: glance
                entities:
                  - entity: sensor.temperature_158d0001d5c2fe
                  - entity: sensor.humidity_158d0001d5c2fe
                  - entity: binary_sensor.fibaro_motion_2_sensor
                  - entity: binary_sensor.fibaro_door_1_sensor
              - type: glance
                entities:
                  - entity: light.vardagsrumslampa
                    name: 'Tak'
                    tap_action: toggle
                  - entity: switch.sonoff2
                    tap_action: toggle
                  - entity: switch.fibaro_wp_5_switch
                    tap_action: toggle
                  - entity: switch.sonoff10
                    name: 'Klotlampa'
                    tap_action: toggle
                  - entity: switch.sonoff1
                    name: 'Fönster'
                    tap_action: toggle
                  # - entity: switch.sonoffs201
                  #   name: 'Balkong'
                  #   tap_action: toggle
                  - entity: switch.sonoffs203
                    tap_action: toggle
          - type: custom:vertical-stack-in-card
            title: 'Köket'
            cards:
              - type: glance
                entities:
                  - entity: binary_sensor.fibaro_motion_3_sensor
                    name: '  '
                  - entity: binary_sensor.fibaro_flood_1_sensor
                    name: '  '
                  - entity: sensor.temperature_158d0001fa6be3
                  - entity: sensor.temperature_158d0001fa6f76
              - type: glance
                entities:
                  - entity: switch.fibaro_wp_8_switch
                    name: 'Fönster'
                    tap_action: toggle
                  - entity: switch.fibaro_wp_11_switch
                    tap_action: toggle
          - type: custom:vertical-stack-in-card
            title: 'Extrarummet'
            cards:
              - type: glance
                entities:
                  - entity: sensor.temperature_158d0001f53709 #extrarummet
                    name: ' '
                  - entity: sensor.humidity_158d0001f53709 #extrarummet 
                    name: ' '
                  - entity: switch.sonoff8
                    name: 'Skåp'
                    tap_action: toggle
                  - entity: switch.sonoff9
                    name: 'Fönster'
                    tap_action: toggle
```
