### ISSUE TITLE
Allow card to be fully conditional

### ISSUE THREAD

**Issue by pplucky** [custom-cards/vertical-stack-in-card#51]
My vertical-stack-in-card is defined like the following:

```
      - type: 'custom:vertical-stack-in-card'
        title: Termóstato Sala
        cards:
          - type: thermostat
            entity: climate.termostato_sala
          - type: entities
            entities:
              - entity: input_select.morning_from_time
              - entity: input_select.morning_to_time
              - entity: input_select.night_from_time
              - entity: input_select.night_to_time
```

I tried combining the usage of [conditional card](https://www.home-assistant.io/lovelace/conditional/) with vertical-stack-in-card, but the following config doesn't seem to work (syntax errors appear when saving):

```
      - type: conditional
        conditions:
          - entity: input_select.season_mode
            state: Winter
        card:
          type: 'custom:vertical-stack-in-card'
          title: Termóstato Sala
          cards:
            - type: thermostat
              entity: climate.termostato_sala
            - type: entities
              entities:
                 - entity: input_select.morning_from_time
                 - entity: input_select.morning_to_time
                 - entity: input_select.night_from_time
                 - entity: input_select.night_to_time
```

After this, I tried the following:
```
      - type: 'custom:vertical-stack-in-card'
        title: Termóstato Sala
        cards:
          - type: conditional
            conditions:
              - entity: input_select.season_mode
                state: Winter
            card:
              type: thermostat
              entity: climate.termostato_sala
          - type: conditional
            conditions:
              - entity: input_select.season_mode
                state: Winter
            card:
              type: entities
              entities:
                - entity: input_select.morning_from_time
                - entity: input_select.morning_to_time
                - entity: input_select.night_from_time
                - entity: input_select.night_to_time
```

and it works, but I get a title only card when condition is not fulfilled.

Would it be possible to make the card fully disappear if no elements are visible?
