### ISSUE TITLE
my config is broken (v 0.1.3)

### ISSUE THREAD

**Issue by TheRealBadRobot** [custom-cards/vertical-stack-in-card#59]
I was on holiday, unfortunately I updated the vertical stack in card via mobile and all of my configuration are broken now. I usd the card modder for eliminate the background of the cards in the vertical stacks but it doesn"t work now.
For example:
before:
![image](https://user-images.githubusercontent.com/46795798/59978736-0cb65680-95e0-11e9-903e-ea4c0cbc6347.png)

The config:

```
card:
  color: white
  entities:
    - cards:
        - cards:
            - card:
                color: 'rgb(255, 165, 0)'
                color_off: 'rgb(30, 144, 255)'
                color_type: icon
                entity: fan.xiaomi_miio_device
                hold_action:
                  action: more-info
                name: légtisztító
                size: 17%
                state:
                  - spin: true
                    styles:
                      card:
                        - box-shadow: 0px 0px 20px 3px var(--paper-item-icon-color)
                        - background-color: 'rgba(57,128,228,0.2)'
                    value: 'on'
                  - styles: null
                    value: 'off'
                styles:
                  card:
                    - transform: scale(0.97)
                    - font-size: 14px
                    - height: 85px
                type: 'custom:button-card'
              style:
                background-color: 'rgba(0,0,0,0.3)'
                background-size: 100% 100%
                border: 'solid 1px rgba(57,128,228,0.6)'
                border-radius: 15px
              type: 'custom:card-modder'
            - card:
                color: 'rgb(255, 165, 0)'
                color_off: 'rgb(30, 144, 255)'
                color_type: icon
                entity: switch.led
                hold_action:
                  action: more-info
                name: LED
                size: 17%
                state:
                  - styles:
                      card:
                        - box-shadow: 0px 0px 20px 3px var(--paper-item-icon-color)
                        - background-color: 'rgba(57,128,228,0.2)'
                    value: 'on'
                  - styles:
                      card: null
                    value: 'off'
                styles:
                  card:
                    - transform: scale(0.97)
                    - font-size: 14px
                    - height: 85px
                type: 'custom:button-card'
              style:
                background-color: 'rgba(0,0,0,0.3)'
                background-size: 100% 100%
                border: 'solid 1px rgba(57,128,228,0.6)'
                border-radius: 15px
              type: 'custom:card-modder'
          type: horizontal-stack
      type: 'custom:vertical-stack-in-card'
    - cards:
        - card:
            entity: input_number.favorite_fan_speed
            name: sebesség
            type: 'custom:slider-entity-row'
          style:
            background-color: 'rgba(0,0,20,0.3)'
            background-size: 100% 100%
          type: 'custom:card-modder'
      type: 'custom:vertical-stack-in-card'
  show_header_toggle: false
  type: entities
style:
  background-color: 'rgba(0,0,20,0.3)'
  background-image: url("/local/pictures/cardback.png")
  background-repeat: no-repeat
  background-size: 100% 100%
  border: 'solid 1px rgba(57,128,228,0.6)'
  border-radius: 15px
type: 'custom:card-modder'
```

now:
![image](https://user-images.githubusercontent.com/46795798/59978750-4edf9800-95e0-11e9-9d0c-3af1ef332555.png)
Unfortunately all cards have this kind of strange behaviour now:
before:
![image](https://user-images.githubusercontent.com/46795798/59978805-c9a8b300-95e0-11e9-978e-84c59a3fdef3.png)

now:
![image](https://user-images.githubusercontent.com/46795798/59978788-949c6080-95e0-11e9-8a97-1f15b0b1038b.png)

Please help me or please send me an older js to try to solve my problem.
