### ISSUE TITLE
Transparency is not the same as with other cards

### ISSUE THREAD

**Issue by wilfredsmit** [custom-cards/vertical-stack-in-card#60]
I like this custom-card and I use it in my modified clear theme. I noticed that the transparency is different than other cards. Look at the example. What could cause this?

<img width="455" alt="Schermafbeelding 2019-07-03 om 21 07 55" src="https://user-images.githubusercontent.com/31591364/60623865-0a27de00-9de4-11e9-8e5f-53313b705d93.png">

**Comment by ofekashery** [comment]
Hey @wilfredsmit 
Can you share your code?

**Comment by wilfredsmit** [comment]
Theme:

```
light:
  # Background image
  background-image: 'center / cover no-repeat url("/local/light.jpg") fixed'

  # Colors
  text-color: '#393d42'                                                           # Grey text
  text-medium-color: '#686e78'                                                    # Medium grey text
  text-light-color: '#95989c'                                                     # Light grey text
  accent-color: '#00a1ff'                                                         # Blue
  background-color: '#F7F8F9'                                                     # Light grey background
  background-color-2: '#F4F5F6'                                                   # Light grey background
  background-card-color: 'rgba(255,255,255,0.7)'                                  # White background
  border-color: '#EAEAEA'                                                         # Light grey border

  # Header
  primary-color: 'var(--text-color)'                                              # Background
  text-primary-color: '#FFF'                                                      # Text
  
  # Left Menu
  paper-listbox-background-color: 'var(--background-color)'                       # Background

  # UI
  paper-card-header-color: 'var(--text-color)'                                    # Title in settings
  primary-background-color: 'var(--background-color)'                             # Background (also title background in left menu)
  
  # Card
  paper-card-background-color: 'var(--background-card-color)'                     # Background
  ha-card-border-radius: '5px'
  dark-primary-color: 'var(--text-color)'
  primary-text-color: 'var(--text-color)'
  paper-listbox-color: 'var(--text-color)'
  light-primary-color: 'var(--text-light-color)'
  secondary-text-color: 'var(--text-medium-color)'
  disabled-text-color: 'var(--text-light-color)'
  paper-dialog-button-color: 'var(--text-color)'
  secondary-background-color: 'var(--background-color-2)'                         # Background more info title

  # Icons
  paper-item-icon-color: 'var(--text-light-color)'                                # Off
  paper-item-icon-active-color: 'var(--accent-color)'                             # On
  
  # Switches
  paper-toggle-button-checked-button-color: '#FFF'                                # Knob On
  paper-toggle-button-checked-bar-color: '#0077FF'                                # Background On
  paper-toggle-button-unchecked-button-color: '#FFF'                              # Knob Off
  paper-toggle-button-unchecked-bar-color: 'var(--disabled-text-color)'           # Background Off
  
  # Shadows
  shadow-elevation-2dp_-_box-shadow: 'inset 0px 0px 0px 1px var(--border-color)'
  shadow-elevation-4dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-6dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-8dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-10dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-12dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-14dp_-_box-shadow: 'var(--shadow-elevation-2dp_-_box-shadow)'
  shadow-elevation-16dp_-_box-shadow: '0px 0px 0px 3px var(--light-color)'

```

Card:

```
cards:
  - artwork: cover
    entity: media_player.woonkamer
    hide:
      controls: false
      icon: false
      info: false
      shuffle: false
      sound_mode: false
      source: false
    name: Radio en Spotify
    shortcuts:
      buttons:
        - id: script.radio_538
          name: Radio 538
          type: script
        - id: script.q_music
          name: Q-Music
          type: script
        - id: script.radio_10
          name: Radio 10
          type: script
        - id: script.veronica
          name: Veronica
          type: script
        - id: script.sky_radio
          name: Sky Radio
          type: script
        - id: script.grandprix_radio
          name: GP Radio
          type: script
        - id: script.bnr
          name: BNR
          type: script
        - id: script.npo_radio_1
          name: Radio 1
          type: script
        - id: script.start_spotify
          name: Spotify
          type: script
        - id: script.playlist_vangelis
          name: Vangelis
          type: script
        - id: script.playlist_eline
          name: Eline
          type: script
        - id: script.playlist_top2000
          name: Top 2000
          type: script
        - id: script.playlist_armin
          name: Armin
          type: script
        - id: script.playlist_zomer2019
          name: Zomer 2019
          type: script
        - id: script.playlist_howard_jones
          name: Howard Jones radio
          type: script
        - id: script.playlist_imagine_dragons
          name: Imagine Dragons radio
          type: script
      columns: 4
      hide_when_off: false
    type: 'custom:mini-media-player'
  - entity: media_player.spotify
    hide:
      controls: true
      hide_when_off: false
      icon: false
      info: true
      name: false
      power: true
      runtime: true
      shuffle: true
      source: false
      volume: true
    type: 'custom:mini-media-player'
type: 'custom:vertical-stack-in-card'
```
