### ISSUE TITLE
Cannot read property 'setConfig' of undefined

### ISSUE THREAD

**Issue by HFsi** [custom-cards/vertical-stack-in-card#64]
I'm getting the subject error when trying to use this card

My config is:
```yaml
- type: 'custom:vertical-stack-in-card'
  title: My Card
  cards:
    - type: glance
      entities:
        - binary_sensor.trafo_status
    - type: entities
      entities:
        - binary_sensor.trafo_status
```

**Comment by shawtux** [comment]
I'm also getting this error.

tried this option
 ```yaml
- type: custom:vertical-stack-in-card
  title: Humedad Plantas
  cards:
    - type: history-graph
      entities:
        - group.all_plants
        - sensor.buganbilia1_moisture
        - sensor.buganbilia2_moisture
        - sensor.buganbilia3_moisture
        - sensor.buganbiliaalta_moisture
        - sensor.buganbiliaalta_moisture
        - sensor.plant_1_moisture
      hours_to_show: 24
      refresh_interval: 0
```

tried this other version of the configuration
```yaml
- type: custom:vertical-stack-in-card
  title: Humedad Plantas
  cards:
  - type: history-graph
    entities:
      - group.all_plants
      - sensor.buganbilia1_moisture
      - sensor.buganbilia2_moisture
      - sensor.buganbilia3_moisture
      - sensor.buganbiliaalta_moisture
      - sensor.buganbiliaalta_moisture
      - sensor.plant_1_moisture
    hours_to_show: 24
    refresh_interval: 0
```
Version: v0.1.3 or v0.1.2


I cannot find any error in the home-assistant.log or anywhere else.

**Comment by HFsi** [comment]
In my case, was a Chrome cache issue. Resetting it was the solution.
But I see in your config that you didn't write custom... Between ' ', like type: 'custom...'

**Comment by shawtux** [comment]
Actually, each time i save my config, it reverts to that.

here is the latest config
```yaml
- type: 'custom:vertical-stack-in-card'
  title: Humedad Plantas
  cards:
    - type: history-graph
      entities:
        - group.all_plants
        - sensor.buganbilia1_moisture
        - sensor.buganbilia2_moisture
        - sensor.buganbilia3_moisture
        - sensor.buganbiliaalta_moisture
        - sensor.buganbiliaalta_moisture
        - sensor.plant_1_moisture
```
