### ISSUE TITLE
No card type configured.

### ISSUE THREAD

**Issue by Gooman-rus** [custom-cards/vertical-stack-in-card#72]
Hassio version 0.103.2.
I have downloaded file to directory "/config/www/vertical-stack-in-card.js".
Added this to yaml resources:
```
resources:
  - type: module
    url: /local/custom-weather-card-chart.js
  - type: module
    url: /local/mini-graph-card-bundle.js?v=0.6.0
  - type: js
    url: /local/vertical-stack-in-card.js?v=0.1.3
```

Trying to use card:
```
- type: 'custom:vertical-stack-in-card'
  title: My Card
  cards:
    - type: entities
      entities:
        - sensor.cpu_temperature
```

Error: 

> No card type found
